### ISSUE TITLE
callback on close()?

### ISSUE THREAD

**Issue by shaunc** [agebrock/tunnel-ssh#66] opened 2018-05-22 14:08 UTC
Shouldn't server.close() take a callback when all of the connections have been shut down? I notice that you call end() on the underlying connections, but if they return false, don't wait for continue.

This may be the source of errors in a test suite I have, which is getting sporadic hanging and/or errors when it opens and closes many connections. Also, I will be deploying to aws lambda, and do want to know if I really have a crisp shutdown without any data lost, without having to linger if connection is already closed.

**Comment by agebrock** [comment] 2018-05-27 03:32
Hi Shaun, I can not find the returning false case you described in this
issue,
Since "end" is not supposed to send false
https://nodejs.org/api/net.html#net_socket_end_data_encoding

If I misunderstood you please correct me in case.

However getting sporadical errors sounds bad and should be addressed,
Looking into the source my best guess is the timeout of 2ms before closing
the server.
To be honest I forgot why the timeout is needed here but I am pretty sure
for whatever I am waiting here it could take longer then 2ms.

I will investigate as soon as I can.
Let me know if you find any further information.


Thanks for reporting
Chris

**Comment by shaunc** [comment] 2018-05-27 03:55
Chris --

I was actually thinking of the ssh2 client.end(), which is a bit opaque to me. 

However, I have working by waiting for the underlying close events -- currently I have the following rather baroque code:
```
      const originalEnd = sftp.end.bind(sftp)
      sftp.end = async () => {
        const tdone = new Promise((res, rej) => {
          let waitingOn = 2
          const check = () => {
            waitingOn -= 1
            if (waitingOn <= 0) {
              res()
            }
          }
          sock.on('close', check)
          tnl.on('close', check)
        })
        await originalEnd()
        sock.end()
        tnl.close()
        await tdone
      }
```
... which works ... but probably shouldn't be necessary. Perhaps I just need to get the order of closing right. :)

NB -- Here, I'm using sftp via a jump server. `tnl` is the tunnel returned by your "connect", `sock` is the socket to localPort, and `sftp` is an ssh2-sftp-client instance I connect via sock to the final sftp server.

**Comment by agebrock** [comment] 2018-06-01 07:58
Still not sure how to reproduce your problem right now. 
I wonder why you are closing the tunnel manually, the proper closing should be done by the tunnel automatically, unless you are using the keepAlive option.

My best guess at this point is you are not using keepAlive but trying to manage the server closing by yourself, if i am guessing right you may try to set keepAlive to true or remove the tnl.close() call from your code and let tunnel-ssh handle the closing (done if all opened connections closed)

By the way i have to correct myself the timeout is ok, and should not be the problem here.

**Comment by shaunc** [comment] 2018-06-01 13:26
Christoph,

Indeed I am using keepalive … probably not necessary here, but a habit after hitting problems once that it solved.

I will play around with how I close.

Thank you! You’re welcome to close if you think this issue not properly demonstrated.

— Shaun

**Comment by agebrock** [comment] 2018-12-15 12:17
Hope it worked out for u

**Closed by agebrock** 2018-12-15 12:17 UTC
